package contactapp.persistence.entity;

import contactapp.support.TestUserFactory;
import contactapp.security.User;
import java.time.Instant;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Validates {@link AppointmentEntity} accessors so coverage includes the persistence layer.
 */
class AppointmentEntityTest {

    @Test
    void constructorStoresInstantFields() {
        Instant instant = Instant.parse("2030-01-01T00:00:00Z");
        User owner = TestUserFactory.createUser("appointment-entity-user");
        AppointmentEntity entity = new AppointmentEntity("A-77", instant, "Future visit", owner);

        assertThat(entity.getAppointmentId()).isEqualTo("A-77");
        assertThat(entity.getAppointmentDate()).isEqualTo(instant);
        assertThat(entity.getDescription()).isEqualTo("Future visit");
        assertThat(entity.getUser()).isEqualTo(owner);
    }

    /**
     * Ensures the surrogate primary key getter is exercised so PIT cannot
     * mutate the {@code getId()} return to an empty value without detection.
     * Uses reflection since the ID is auto-generated by JPA.
     */
    @Test
    void idGetterReturnsSurrogateKey() throws Exception {
        AppointmentEntity entity = new AppointmentEntity();
        java.lang.reflect.Field idField = AppointmentEntity.class.getDeclaredField("id");
        idField.setAccessible(true);
        idField.set(entity, 77L);

        assertThat(entity.getId()).isEqualTo(77L);
    }

    /**
     * JPA proxies rely on the protected constructor; setters must therefore populate
     * every field without additional validation.
     */
    @Test
    void settersWorkWhenEntityCreatedByHibernate() {
        AppointmentEntity entity = new AppointmentEntity();

        Instant instant = Instant.parse("2031-02-03T00:00:00Z");
        entity.setAppointmentId("A-88");
        entity.setAppointmentDate(instant);
        entity.setDescription("Proxy update");
        User owner = TestUserFactory.createUser("appointment-entity-mutable");
        entity.setUser(owner);

        assertThat(entity.getAppointmentId()).isEqualTo("A-88");
        assertThat(entity.getAppointmentDate()).isEqualTo(instant);
        assertThat(entity.getDescription()).isEqualTo("Proxy update");
        assertThat(entity.getUser()).isEqualTo(owner);
    }
}
