package contactapp.persistence.entity;

import contactapp.support.TestUserFactory;
import contactapp.security.User;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Covers the mutable {@link ContactEntity} accessor surface so JaCoCo counts the JPA layer.
 */
class ContactEntityTest {

    @Test
    void constructorAndGettersExposeFields() {
        User owner = TestUserFactory.createUser("contact-entity-user");
        ContactEntity entity = new ContactEntity("C-100", "Alice", "Smith", "1112223333", "123 Main", owner);

        assertThat(entity.getContactId()).isEqualTo("C-100");
        assertThat(entity.getFirstName()).isEqualTo("Alice");
        assertThat(entity.getLastName()).isEqualTo("Smith");
        assertThat(entity.getPhone()).isEqualTo("1112223333");
        assertThat(entity.getAddress()).isEqualTo("123 Main");
        assertThat(entity.getUser()).isEqualTo(owner);
    }

    /**
     * Ensures the surrogate primary key getter is exercised so PIT cannot
     * mutate the {@code getId()} return to an empty value without detection.
     * Uses reflection since the ID is auto-generated by JPA.
     */
    @Test
    void idGetterReturnsSurrogateKey() throws Exception {
        ContactEntity entity = new ContactEntity();
        java.lang.reflect.Field idField = ContactEntity.class.getDeclaredField("id");
        idField.setAccessible(true);
        idField.set(entity, 42L);

        assertThat(entity.getId()).isEqualTo(42L);
    }

    /**
     * The protected no-args constructor exists strictly for Hibernate; this test ensures
     * setters keep working even when an empty proxy is materialized.
     */
    @Test
    void jpaConstructorAllowsPropertyMutation() {
        ContactEntity entity = new ContactEntity();

        entity.setFirstName("Jane");
        entity.setLastName("Doe");
        entity.setPhone("9998887777");
        entity.setAddress("456 Elm");
        User owner = TestUserFactory.createUser("contact-entity-mutable");
        entity.setUser(owner);
        entity.setFirstName("Janet"); // ensure setters overwrite values

        assertThat(entity.getFirstName()).isEqualTo("Janet");
        assertThat(entity.getLastName()).isEqualTo("Doe");
        assertThat(entity.getPhone()).isEqualTo("9998887777");
        assertThat(entity.getAddress()).isEqualTo("456 Elm");
        assertThat(entity.getUser()).isEqualTo(owner);
    }

    @Test
    void versionGetterReturnsAssignedValue() {
        ContactEntity entity = new ContactEntity();
        entity.setVersion(3L);
        assertThat(entity.getVersion()).isEqualTo(3L);
    }
}
