package contactapp.persistence.entity;

import contactapp.domain.ProjectStatus;
import contactapp.support.TestUserFactory;
import contactapp.security.User;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Covers the mutable {@link ProjectEntity} accessor surface so JaCoCo counts the JPA layer.
 */
class ProjectEntityTest {

    @Test
    void constructorAndGettersExposeFields() {
        User owner = TestUserFactory.createUser("project-entity-user");
        ProjectEntity entity = new ProjectEntity("P-100", "Project Alpha", "Initial description", ProjectStatus.ACTIVE, owner);

        assertThat(entity.getProjectId()).isEqualTo("P-100");
        assertThat(entity.getName()).isEqualTo("Project Alpha");
        assertThat(entity.getDescription()).isEqualTo("Initial description");
        assertThat(entity.getStatus()).isEqualTo(ProjectStatus.ACTIVE);
        assertThat(entity.getUser()).isEqualTo(owner);
    }

    /**
     * Ensures the surrogate primary key getter is exercised so PIT cannot
     * mutate the {@code getId()} return to an empty value without detection.
     * Uses reflection since the ID is auto-generated by JPA.
     */
    @Test
    void idGetterReturnsSurrogateKey() throws Exception {
        ProjectEntity entity = new ProjectEntity();
        java.lang.reflect.Field idField = ProjectEntity.class.getDeclaredField("id");
        idField.setAccessible(true);
        idField.set(entity, 42L);

        assertThat(entity.getId()).isEqualTo(42L);
    }

    /**
     * The protected no-args constructor exists strictly for Hibernate; this test ensures
     * setters keep working even when an empty proxy is materialized.
     */
    @Test
    void jpaConstructorAllowsPropertyMutation() {
        ProjectEntity entity = new ProjectEntity();

        entity.setName("Beta Project");
        entity.setDescription("Detailed description");
        entity.setStatus(ProjectStatus.ON_HOLD);
        User owner = TestUserFactory.createUser("project-entity-mutable");
        entity.setUser(owner);
        entity.setName("Gamma Project"); // ensure setters overwrite values

        assertThat(entity.getName()).isEqualTo("Gamma Project");
        assertThat(entity.getDescription()).isEqualTo("Detailed description");
        assertThat(entity.getStatus()).isEqualTo(ProjectStatus.ON_HOLD);
        assertThat(entity.getUser()).isEqualTo(owner);
    }

    @Test
    void versionGetterReturnsAssignedValue() {
        ProjectEntity entity = new ProjectEntity();
        entity.setVersion(7L);
        assertThat(entity.getVersion()).isEqualTo(7L);
    }
}
