package contactapp.persistence.entity;

import contactapp.support.TestUserFactory;
import contactapp.security.User;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Ensures {@link TaskEntity} exposes predictable getters/setters for Hibernate and the mappers.
 */
class TaskEntityTest {

    @Test
    void constructorInitializesAllFields() {
        User owner = TestUserFactory.createUser("task-entity-user");
        TaskEntity entity = new TaskEntity("T-5", "Write docs", "Explain persistence layer", owner);

        assertThat(entity.getTaskId()).isEqualTo("T-5");
        assertThat(entity.getName()).isEqualTo("Write docs");
        assertThat(entity.getDescription()).isEqualTo("Explain persistence layer");
        assertThat(entity.getUser()).isEqualTo(owner);
    }

    /**
     * Ensures the surrogate primary key getter is exercised so PIT cannot
     * mutate the {@code getId()} return to an empty value without detection.
     * Uses reflection since the ID is auto-generated by JPA.
     */
    @Test
    void idGetterReturnsSurrogateKey() throws Exception {
        TaskEntity entity = new TaskEntity();
        java.lang.reflect.Field idField = TaskEntity.class.getDeclaredField("id");
        idField.setAccessible(true);
        idField.set(entity, 99L);

        assertThat(entity.getId()).isEqualTo(99L);
    }

    /**
     * Hibernate uses the protected constructor, so verify setters function when the entity
     * is populated via reflection.
     */
    @Test
    void settersUpdateStateWhenProxyMaterialized() {
        TaskEntity entity = new TaskEntity();

        entity.setTaskId("T-9");
        entity.setName("Refresh docs");
        entity.setDescription("Update README coverage notes");
        User owner = TestUserFactory.createUser("task-entity-mutable");
        entity.setUser(owner);

        assertThat(entity.getTaskId()).isEqualTo("T-9");
        assertThat(entity.getName()).isEqualTo("Refresh docs");
        assertThat(entity.getDescription()).isEqualTo("Update README coverage notes");
        assertThat(entity.getUser()).isEqualTo(owner);
    }
}
